### ISSUE TITLE
Add Visual Studio 2017 Support

### ISSUE THREAD

**Issue by jacksondaw** [cyotek/Cyotek.AddProjects#13]
Not a real problem, because the extension works without any issues in Visual Studio 2017. However, the installer does notify the user that it could cause visual studio to become unstable.

**Comment by cyotek** [comment]
Hello

See pull request #7 - I've been slightly busy and still haven't gotten around to getting it tested yet. I shall strive to get it done this weekend or early next week, sorry for the delay!

Regards;
Richard Moss

**Comment by jacksondaw** [comment]
Hey Richard,

Yep, I should have looked before creating the issue. It is a duplicate of #7
