### ISSUE TITLE
Support VS 2017

### ISSUE THREAD

**Issue by wezzix** [cyotek/Cyotek.AddProjects#15]
I love this extension, saves me a bunch of time on each new project. 
Please add support for Visual Studio 2017. Thanks!

**Comment by cyotek** [comment]
Hello,

I finally got around to updating the extension to support VS2017. However, as installing VS2017 breaks the ability to compile VS2015 extensions I've published the VS2017 version with a new ID as I wasn't able to make use of PR #7 to make one happy project.

No other code changes have been made; I've simply tested that a) it doesn't give compatibility warnings when trying to install and b) adds a project to the solution.

You can find it [here](https://marketplace.visualstudio.com/items?itemName=RichardJMoss.AddExistingProjects-19444).

Let me know if you encounter any problems; I don't actually use this extension quite as much as I used to as I've converted the bulk of my private libraries into NuGet packages so I haven't extensively used it on VS2017 yet.

Regards;
Richard Moss

**Comment by wezzix** [comment]
I appreciate your effort!

However the link you sent to 2017 version appears to be broken as well as the link on the other page<https://marketplace.visualstudio.com/items?itemName=RichardJMoss.AddExistingProjects> “Looking for the Visual Studio 2017 version?<https://marketplace.visualstudio.com/vsgallery/a8cce4b4-2c1c-47ed-a0ea-310831d7513b>“
https://marketplace.visualstudio.com/items?itemName=RichardJMoss.AddExistingProjects-19444
We're sorry, the page you requested cannot be found!

On the previous page, the Download button does nothing but reload the page (in Chrome)…
Is this something you could fix?

Thanks,
Markus

**Comment by cyotek** [comment]
Hello,

After uploading it I think I forgot to check the box to actually publish it. I did that yesterday but the download button was still doing nothing. Tested again today and now download works - hopefully it works now for you too.

**Comment by wezzix** [comment]
Yes it works now. I tested the extension and it works like before, same history even :)
(There was a local issue in Chrome with the Download button increasing the count but not downloading anything, but a different Chrome worked as well as using Edge. )

Thank you for maintaining my favourite VS extension!
