### ISSUE TITLE
[Feature Request] Add support for vs2022

### ISSUE THREAD

**Issue by JKamsker** [cyotek/Cyotek.AddProjects#19]
Please see title

**Comment by cyotek** [comment]
Thanks for the feature request. I need to do some testing to make sure it works with as little code changes as possible, assuming it will more or less work out the box I will look at issuing an update fairly soon.

**Comment by cyotek** [comment]
Hello - new package (currently preview, I've given it some limited testing but that is it) is available from the marketplace: https://marketplace.visualstudio.com/items?itemName=cyotek.cyotekaddprojectsvs2022
