### ISSUE TITLE
Broken support for VS2012

### ISSUE THREAD

**Issue by cyotek** [cyotek/Cyotek.AddProjects#4]
AlexO comments

> Does not work on VS2012
> 
> ``` xml
> <entry>
> <record>457</record>
> <time>2016/05/19 21:30:01.242</time>
> <type>Error</type>
> <source>VisualStudio</source>
> <description>End package load [AddProjectsPackage]</description>
> <guid>{AF385D18-DD14-4C1B-A4AD-3E69C525312F}</guid>
> <hr>80004005 - E_FAIL</hr>
> <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.11.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
> </entry>
> ```

Need to either figure out if extensions compiled with VS2015 can be compatible with earlier versions, or remove the support from the manifest.

**Comment by info-wes** [comment]
You need to install the Visual Studio 2012 Shell. Install the Isolated one first and then the Integrated one. I found it hard to get the installers as Microsoft has seemingly removed them from their downloads. You can get them from Softpedia, though:

http://www.softpedia.com/get/Programming/Other-Programming-Files/Visual-Studio-Shell.shtml

**Comment by cyotek** [comment]
Closing this as I just don't have time to try and support something this old, and evidently no one cares about VS2012 anyway!
